### ISSUE TITLE
Ekran logowania - brak kursora w polu tekstowym

### ISSUE THREAD

**Issue by krzaq90** [c3ph3us/datezone#1]
Brak kursora W polach tekstowych "nazwa użytkownika" oraz "hasło" na ekranie logowania. Błąd występuje na tablecie Samsung Galaxy Tab S (SM-T805) z systemem Android 5.0.2. W polu tekstowym wiadomosci widoczny jest już kursor.
W/w błędy nie zauważyłem na telefonie LG L7 II z systemem Android 4.1.2, tam na ekranie logowania widoczny jest kursor.

**Comment by c3ph3us** [comment]
@Dresik proszę o podawanie wersji aplikacji przy tworzeniu issue

**Comment by c3ph3us** [comment]
Problem rozwiązany w wersji:
0.2.4 beta2 4857
