### ISSUE TITLE
0.2.0 beta2 4759 -> okno wysyłania wiadomości w konwersacji nie pokazuje się 

### ISSUE THREAD

**Issue by c3ph3us** [c3ph3us/datezone#3]
<b>dotyczy: </b>
wersja android (AOSP): .4.4.4 
model telefonu: c6903

![11262260_10200446476321844_205818770_n](https://cloud.githubusercontent.com/assets/10565704/7666883/4bed85ea-fbf6-11e4-8196-dcf41b4ddb8a.jpg)

**Comment by krzaq90** [comment]
Problem występuje również na telefonie LG L7 II - Android 4.1.1

**Comment by c3ph3us** [comment]
Problem rozwiązany w wersji:
0.2.4 beta2 4857
