### ISSUE TITLE
0.2.2 beta2 4759 -> ekran logowania 2 oraz ustawienia domyslnego uzytkownika

### ISSUE THREAD

**Issue by krzaq90** [c3ph3us/datezone#5]
1. W orientacji poziomej przy mniejszej rozdzielczosci ekranu nie widac tekstu Pamiętaj...
   Urzadzenie: Galaxy Note II (GT-7100) Android 4.4.2
   ![img_4619](https://cloud.githubusercontent.com/assets/12463527/7668292/5df33d2c-fc30-11e4-9206-04310ee4f410.JPG)
2. Po wylogowaniu na liscie uzytkownikow brak loginu - jest dodaj nowe konto ale po kliknieciu jestesmy logowani na swoje konto. 
   Urzadzenie: Galaxy Tab S (SM-T805) Android 5.0.2
   ![img_4617](https://cloud.githubusercontent.com/assets/12463527/7668296/a6c53c58-fc30-11e4-860f-073bc33ee2fe.JPG)
3. Przycisk "powrót" - po jego wcisnieciu aplikacja pokazuje ekran przed i po wylogowaniu ale mamy pelen dostep do ustawien, pulpitu oraz wiadomosc. 
   Urzadzenie: Tab S i Note II
   ![img_4618](https://cloud.githubusercontent.com/assets/12463527/7668299/d01d9a0a-fc30-11e4-8680-a7d2aff94b6a.JPG)
   ![img_4615](https://cloud.githubusercontent.com/assets/12463527/7668300/d6f9ad28-fc30-11e4-8a64-0abc2455af2a.JPG)
   4.Ustawienia -  brak mozliwosci wyboru domyslnego użytkownika 
   Urzadzenie : Tab S i Note II
   ![img_4611](https://cloud.githubusercontent.com/assets/12463527/7668301/f03192d8-fc30-11e4-9904-0007f912ed79.PNG)
   ![img_4608](https://cloud.githubusercontent.com/assets/12463527/7668302/f6484f04-fc30-11e4-8443-45c4ae6a90c5.PNG)

**Comment by c3ph3us** [comment]
Problem nr 1 i 2  rozwiązany w wersji:
0.2.4 beta2 4857 problem 3 częściowo.

**Comment by c3ph3us** [comment]
usunięto w wersji 0.2.6 beta2 6414 [ dostępna dla testerów w google play](https://play.google.com/apps/testing/com.datezone.beta2)
