### ISSUE TITLE
0.2.4 beta2 4857 -> ekran logowania, błąd po wyjściu z aplikacji do pulpitu systemowego za pomocą przycisku "cofnij"

### ISSUE THREAD

**Issue by krzaq90** [c3ph3us/datezone#6]
Aplikacja testowana na urządzeniach:
a. Samsung Galaxy Tab S (SM-T805) - Android 5.0.2
b. Samsung Galaxy Note II (GT-N7100) - Android 4.4.2
c. LG L7 II (P710) - Android 4.1.1

Błędy:
1. Nie czytelny ekran logowania.
 [a] kolor kursora zalewa się z tłem okna logowania,
 [b] kolor czcionki w polu tekstowym zalewa się z tłem pola tekstowego,
 [c] błąd nie występuje na urzadzeniu.

![image](https://cloud.githubusercontent.com/assets/12463527/7669993/b257ffd2-fc90-11e4-932e-aead7143d108.jpg)
![image](https://cloud.githubusercontent.com/assets/12463527/7669994/b2d78342-fc90-11e4-9215-b140fa525e8a.jpg)
1. Po wyjściu do pulpitu systemowego za pomocą przycisku "cofnij" o ponownym wejściu aplikacja pokazuje ekran "przed i po wylogowaniu" mimo że nie nastąpiło wylogowanie z aplikacji. Błąd występuje na urządzeniach [a, b, c]
   ![image](https://cloud.githubusercontent.com/assets/12463527/7670000/c780a6de-fc90-11e4-85ec-b0c3981e2f97.jpg)
   ![image](https://cloud.githubusercontent.com/assets/12463527/7670002/c7d4f31a-fc90-11e4-9c6e-1d0df5519975.jpg)
   ![image](https://cloud.githubusercontent.com/assets/12463527/7670001/c7d169de-fc90-11e4-86a3-4e8694b46eee.jpg)

**Comment by c3ph3us** [comment]
błąd  występuje już w #5

**Comment by c3ph3us** [comment]
usunięto w wersji 0.2.6 beta2 6414 [ dostępna dla testerów w google play](https://play.google.com/apps/testing/com.datezone.beta2)
